### ISSUE TITLE
What shell config are you using?

### ISSUE THREAD

**Issue by steelbrain** [chinanf-boy/node-modules-size-snapshot#1]
Unrelated to repo, apologies.

But what shell config/theme are you using in the screenshots in README? Can you please provide a resource / link for other people who would want to have it?

Cheers

**Comment by chinanf-boy** [comment]
Look Great right ?!

you can Check https://github.com/sindresorhus/ama/issues/428#issuecomment-258599158

**Comment by steelbrain** [comment]
It looks beautiful! Thank you for the link
